In [8]:
!pip install pandas numpy

Collecting pandas
  Downloading pandas-3.0.3-cp313-cp313-win_amd64.whl.metadata (19 kB)
Collecting numpy
  Downloading numpy-2.5.1-cp313-cp313-win_amd64.whl.metadata (6.6 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in E:\Miniconda\Lib\site-packages (from pandas) (2.9.0.post0)
Collecting tzdata (from pandas)
  Using cached tzdata-2026.2-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in E:\Miniconda\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.3-cp313-cp313-win_amd64.whl (9.8 MB)
   ---------------------------------------- 0.0/9.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.8 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.8 MB ? eta -:--:--
   -- ------------------------------------- 0.5/9.8 MB 1.2 MB/s eta 0:00:08
   -- ------------------------------------- 0.5/9.8 MB 1.2 MB/s eta 0:00:08
   -- ------------------------------------- 0.5/9.8 MB 1.2 MB/s eta 0:00:08
   --- ------------------------------------ 0.8/9.8 MB 596.7 kB/s eta 0:00:16
   ----- ---------------------------------- 1.3/9.8 MB 909.2 kB/s eta 0:00:10
   ----- ---------------------------------- 1.3/9.8 MB 909.2 kB/s eta 0:00:10
   -------- ------------------------------- 2.1/9.8 MB 1.2 MB/s eta 0:00:07
   --------- ------------------------------ 2.4/9.8 MB 1.3 MB/s eta 0:00:06
   ---------- ----------------------------- 2.6/9.8 MB 1.2 MB/s eta 0:00:06
   ---------- ----------------------------- 2.6/9.8 MB 1.2 MB/s eta 0:00:06
   ----------- ---------------------------- 2.9/9.8 MB 1.1 MB/s eta 0:00:07
   ------------ --------------------------- 3.1/9.8 MB 1.1 MB/s eta 0:00:06
   ------------- -------------------------- 3.4/9.8 MB 1.1 MB/s eta 0:00:06
   --------------- ------------------------ 3.7/9.8 MB 1.1 MB/s eta 0:00:06
   ---------------- ----------------------- 3.9/9.8 MB 1.1 MB/s eta 0:00:06
   ---------------- ----------------------- 3.9/9.8 MB 1.1 MB/s eta 0:00:06
   ----------------- ---------------------- 4.2/9.8 MB 1.1 MB/s eta 0:00:06
   ------------------ --------------------- 4.5/9.8 MB 1.1 MB/s eta 0:00:05
   ------------------- -------------------- 4.7/9.8 MB 1.1 MB/s eta 0:00:05
   -------------------- ------------------- 5.0/9.8 MB 1.1 MB/s eta 0:00:05
   --------------------- ------------------ 5.2/9.8 MB 1.1 MB/s eta 0:00:05
   ---------------------- ----------------- 5.5/9.8 MB 1.1 MB/s eta 0:00:04
   ----------------------- ---------------- 5.8/9.8 MB 1.1 MB/s eta 0:00:04
   ----------------------- ---------------- 5.8/9.8 MB 1.1 MB/s eta 0:00:04
   ------------------------ --------------- 6.0/9.8 MB 1.1 MB/s eta 0:00:04
   ------------------------- -------------- 6.3/9.8 MB 1.1 MB/s eta 0:00:04
   ------------------------- -------------- 6.3/9.8 MB 1.1 MB/s eta 0:00:04
   -------------------------- ------------- 6.6/9.8 MB 1.1 MB/s eta 0:00:04
   --------------------------- ------------ 6.8/9.8 MB 1.1 MB/s eta 0:00:03
   ----------------------------- ---------- 7.1/9.8 MB 1.1 MB/s eta 0:00:03
   ----------------------------- ---------- 7.1/9.8 MB 1.1 MB/s eta 0:00:03
   ------------------------------ --------- 7.3/9.8 MB 1.0 MB/s eta 0:00:03
   ------------------------------- -------- 7.6/9.8 MB 1.0 MB/s eta 0:00:03
   -------------------------------- ------- 7.9/9.8 MB 1.0 MB/s eta 0:00:02
   -------------------------------- ------- 7.9/9.8 MB 1.0 MB/s eta 0:00:02
   --------------------------------- ------ 8.1/9.8 MB 1.0 MB/s eta 0:00:02
   ---------------------------------- ----- 8.4/9.8 MB 1.0 MB/s eta 0:00:02
   ----------------------------------- ---- 8.7/9.8 MB 1.0 MB/s eta 0:00:02
   ------------------------------------ --- 8.9/9.8 MB 1.0 MB/s eta 0:00:01
   ------------------------------------ --- 8.9/9.8 MB 1.0 MB/s eta 0:00:01
   ------------------------------------- -- 9.2/9.8 MB 1.0 MB/s eta 0:00:01
   -------------------------------------- - 9.4/9.8 MB 1.0 MB/s eta 0:00:01
   -------------------------------------- - 9.4/9.8 MB 1.0 MB/s eta 0:00:01
   ---------------------------------------- 9.8/9.8 MB 1.0 MB/s  0:00:09
Downloading numpy-2.5.1-cp313-cp313-win_amd64.whl (12.4 MB)
   ---------------------------------------- 0.0/12.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.4 MB ? eta -:--:--
    --------------------------------------- 0.3/12.4 MB ? eta -:--:--
   - -------------------------------------- 0.5/12.4 MB 1.1 MB/s eta 0:00:12
   -- ------------------------------------- 0.8/12.4 MB 1.0 MB/s eta 0:00:12
   --- ------------------------------------ 1.0/12.4 MB 1.0 MB/s eta 0:00:12
   --- ------------------------------------ 1.0/12.4 MB 1.0 MB/s eta 0:00:12
   ---- ----------------------------------- 1.3/12.4 MB 1.1 MB/s eta 0:00:11
   ----- ---------------------------------- 1.6/12.4 MB 999.1 kB/s eta 0:00:11
   ----- ---------------------------------- 1.8/12.4 MB 1.0 MB/s eta 0:00:11
   ----- ---------------------------------- 1.8/12.4 MB 1.0 MB/s eta 0:00:11
   ------ --------------------------------- 2.1/12.4 MB 985.0 kB/s eta 0:00:11
   ------- -------------------------------- 2.4/12.4 MB 1.0 MB/s eta 0:00:10
   -------- ------------------------------- 2.6/12.4 MB 1.0 MB/s eta 0:00:10
   --------- ------------------------------ 2.9/12.4 MB 1.0 MB/s eta 0:00:10
   ---------- ----------------------------- 3.1/12.4 MB 1.0 MB/s eta 0:00:09
   ---------- ----------------------------- 3.4/12.4 MB 1.0 MB/s eta 0:00:09
   ----------- ---------------------------- 3.7/12.4 MB 1.1 MB/s eta 0:00:09
   ------------ --------------------------- 3.9/12.4 MB 1.1 MB/s eta 0:00:08
   ------------- -------------------------- 4.2/12.4 MB 1.1 MB/s eta 0:00:08
   -------------- ------------------------- 4.5/12.4 MB 1.1 MB/s eta 0:00:08
   --------------- ------------------------ 4.7/12.4 MB 1.1 MB/s eta 0:00:08
   ---------------- ----------------------- 5.0/12.4 MB 1.1 MB/s eta 0:00:07
   ---------------- ----------------------- 5.2/12.4 MB 1.1 MB/s eta 0:00:07
   ----------------- ---------------------- 5.5/12.4 MB 1.1 MB/s eta 0:00:07
   ----------------- ---------------------- 5.5/12.4 MB 1.1 MB/s eta 0:00:07
   ------------------ --------------------- 5.8/12.4 MB 1.1 MB/s eta 0:00:07
   ------------------- -------------------- 6.0/12.4 MB 1.1 MB/s eta 0:00:06
   -------------------- ------------------- 6.3/12.4 MB 1.1 MB/s eta 0:00:06
   --------------------- ------------------ 6.6/12.4 MB 1.1 MB/s eta 0:00:06
   --------------------- ------------------ 6.8/12.4 MB 1.1 MB/s eta 0:00:06
   ---------------------- ----------------- 7.1/12.4 MB 1.1 MB/s eta 0:00:05
   ----------------------- ---------------- 7.3/12.4 MB 1.1 MB/s eta 0:00:05
   ------------------------ --------------- 7.6/12.4 MB 1.1 MB/s eta 0:00:05
   ------------------------- -------------- 7.9/12.4 MB 1.1 MB/s eta 0:00:05
   -------------------------- ------------- 8.1/12.4 MB 1.1 MB/s eta 0:00:04
   --------------------------- ------------ 8.4/12.4 MB 1.1 MB/s eta 0:00:04
   --------------------------- ------------ 8.7/12.4 MB 1.1 MB/s eta 0:00:04
   ---------------------------- ----------- 8.9/12.4 MB 1.1 MB/s eta 0:00:04
   ----------------------------- ---------- 9.2/12.4 MB 1.1 MB/s eta 0:00:03
   ------------------------------ --------- 9.4/12.4 MB 1.1 MB/s eta 0:00:03
   ------------------------------- -------- 9.7/12.4 MB 1.1 MB/s eta 0:00:03
   ------------------------------- -------- 9.7/12.4 MB 1.1 MB/s eta 0:00:03
   -------------------------------- ------- 10.0/12.4 MB 1.1 MB/s eta 0:00:03
   -------------------------------- ------- 10.2/12.4 MB 1.1 MB/s eta 0:00:02
   --------------------------------- ------ 10.5/12.4 MB 1.1 MB/s eta 0:00:02
   ---------------------------------- ----- 10.7/12.4 MB 1.1 MB/s eta 0:00:02
   ------------------------------------ --- 11.3/12.4 MB 1.1 MB/s eta 0:00:02
   ------------------------------------ --- 11.3/12.4 MB 1.1 MB/s eta 0:00:02
   ------------------------------------- -- 11.5/12.4 MB 1.1 MB/s eta 0:00:01
   ------------------------------------- -- 11.8/12.4 MB 1.1 MB/s eta 0:00:01
   -------------------------------------- - 12.1/12.4 MB 1.1 MB/s eta 0:00:01
   -------------------------------------- - 12.1/12.4 MB 1.1 MB/s eta 0:00:01
   ---------------------------------------  12.3/12.4 MB 1.1 MB/s eta 0:00:01
   ---------------------------------------- 12.4/12.4 MB 1.1 MB/s  0:00:11
Using cached tzdata-2026.2-py2.py3-none-any.whl (349 kB)
Installing collected packages: tzdata, numpy, pandas

   ---------------------------------------- 0/3 [tzdata]
   ---------------------------------------- 0/3 [tzdata]
   ---------------------------------------- 0/3 [tzdata]
   ---------------------------------------- 0/3 [tzdata]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]

In [9]:
pip install pandas numpy

Requirement already satisfied: pandas in e:\Miniconda\Lib\site-packages (3.0.3)
Requirement already satisfied: numpy in e:\Miniconda\Lib\site-packages (2.5.1)
Requirement already satisfied: python-dateutil>=2.8.2 in e:\Miniconda\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in e:\Miniconda\Lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in e:\Miniconda\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [10]:
import pandas as pd
import numpy as np

In [11]:
# 'pd.read_csv' ka matlab hai CSV file ko parho aur use aik table (DataFrame) mein badlo
df = pd.read_csv("weather.csv")

# Sirf 'df' likhne se wo poora table screen par show ho jata hai
df

       date      city  temperature  humidity
0  5/1/2024  new york           65        56
1  5/2/2024  new york           66        58
2  5/3/2024  new york           68        60
3  5/1/2024     dubai           75        80
4  5/2/2024     dubai           78        83
5  5/3/2024     dubai           82        85
6  5/1/2024   beijing           80        26
7  5/2/2024   beijing           77        30
8  5/3/2024   beijing           79        35

In [12]:
# Hum Python ko bol rahay hain: City ko side par rakho aur Date ko upar columns bana do
pivoted_df = df.pivot(index='city', columns='date')

# Naye badlay huay table ko dekhne ke liye
pivoted_df

         temperature                   humidity
date        5/1/2024 5/2/2024 5/3/2024 5/1/2024 5/2/2024 5/3/2024
city
beijing           80       77       79       26       30       35
dubai             75       78       82       80       83       85
new york          65       66       68       56       58       60

In [13]:
# Is dafa hum ne aakhir mein 'values="humidity"' ka izafa kiya hai
humidity_df = df.pivot(index='city', columns='date', values='humidity')

# Naye filtered table ko dekhne ke liye
humidity_df

date      5/1/2024  5/2/2024  5/3/2024
city
beijing         26        30        35
dubai           80        83        85
new york        56        58        60

In [17]:
# `/content/drive/...` mita kar sirf file ka naam likhein
df2 = pd.read_csv("weather2.csv")

# Data ko dekhne ke liye
df2

       date      city  temperature  humidity
0  5/1/2024  new york           65        56
1  5/1/2024  new york           61        54
2  5/2/2024  new york           70        60
3  5/2/2024  new york           72        62
4  5/1/2024     dubai           75        80
5  5/1/2024     dubai           78        83
6  5/2/2024     dubai           82        85
7  5/2/2024     dubai           80        26

In [18]:
# Teesri weather file ko load kiya jismein pure saal ka data hai
df3 = pd.read_csv("weather3.csv")

# Data ko dekhne ke liye
df3

        date      city  temperature  humidity
0   5/1/2024  new york           65        56
1   5/2/2024  new york           61        54
2   5/3/2024  new york           70        60
3  12/1/2024  new york           30        50
4  12/2/2024  new york           28        52
5  12/3/2024  new york           25        51

In [21]:
# pd.Grouper(freq='ME') ka matlab hai Month-End ke hisab se group karo
monthly_summary = df3.pivot_table(index=pd.Grouper(freq='ME', key='date'), columns='city')

# Final result dekhne ke liye
monthly_summary

             humidity temperature
city         new york    new york
date
2024-05-31  56.666667   65.333333
2024-12-31  51.000000   27.666667